### ISSUE TITLE
Git revision in document

### ISSUE THREAD

**Issue by ygworldr** [xu-cheng/latex-action#91] opened 2022-03-31 14:51 UTC
I am using the below code to have the git revision in the document:

```latex
% Git support.
\usepackage{xstring}
\usepackage{catchfile}
\CatchFileDef{\HEAD}{.git/refs/heads/main}{}
\newcommand{\gitrevision}{%
  \StrLeft{\HEAD}{7}%
}
```

However, I get this error when I run the action: `Package catchfile Error: File `.git/refs/heads/main' not found.` which is probably because the git files are not copied to the docker image.

Is there an option to add this file?

Or a way to specify a version somehow…

Thank you.

**Comment by xu-cheng** [comment] 2022-04-04 21:05
The git repository should be mirrored to the docker container. Could you check whether you pass the correct the path to the file? You can run `ls` command using `pre_compile` input to inspect the directory.

**Comment by ygworldr** [comment] 2022-04-05 08:13
I just tried. Yes, `.git` is there. However, the file I want is not despite it being in the main repo.

```bash
ls: .git/refs/heads/main: No such file or directory
```

I wonder if it is an artefact of the `git clone` specific command… I guess I could use a git command (`git describe --tags --always --dirty --match="v*"`) to get then version, put that in an environment variable, and [read if from LaTeX](https://tex.stackexchange.com/questions/62010/can-i-access-system-environment-variables-from-latex-for-instance-home).

**Comment by xu-cheng** [comment] 2022-04-05 09:04
There is a `GITHUB_SHA` env available in GitHub action you can use directly. I will close this issue as it is not a bug of this action.

**Closed by xu-cheng** 2022-04-05 09:04 UTC

**Comment by ygworldr** [comment] 2022-04-05 10:02
In case anyone else stumbles onto this: I could not get it to work. I used this in the action:

```bash
echo "GITVERSION=${{ env.GITHUB_SHA }}" >> $GITHUB_ENV
```

With the [code from stack](https://tex.stackexchange.com/questions/62010/can-i-access-system-environment-variables-from-latex-for-instance-home) and this is the error I get:

```
./file.tex:143: LaTeX Error: There's no line here to end.
```

This line has nothing in it. ¯\\\_(ツ)\_/¯
